language: python
python:
    - "3.6"

cache:
    apt: true
    directories:
    - $HOME/.cache/pip

addons:
    postgresql: "9.6"
    apt:
        packages:
            - expect-dev
            - python-lxml

install:
    - wget https://raw.githubusercontent.com/odoo/odoo/13.0/requirements.txt -O requirements.txt
    - pip3 install -r requirements.txt
    - mkdir src
    - git clone --single-branch -b 13.0 https://github.com/odoo/odoo src/odoo

script:
    - src/odoo/odoo-bin --stop-after-init -d test -ibase
